import json
from pathlib import Path
from backend.app.agents.base import AgentContext, AgentRunner, compute_confidence, evidence, STRICT_REALTIME_PROMPT
from backend.app.agents.fallbacks import build_explanations, parse_json_object
from backend.app.schemas import AgentResult, GenerationMessage

MODELS_DIR = Path(__file__).resolve().parents[3] / "models" / "xgboost"

class ExplainabilityAgent(AgentRunner):
    agent_name = "explainability"

    async def run(self, ctx: AgentContext) -> AgentResult:
        return await self._timed_run_async(ctx, self._run_impl)

    async def _run_impl(self, ctx: AgentContext) -> AgentResult:
        prediction = ctx.outputs.get("prediction", {})
        rag = ctx.rag
        risk = ctx.outputs.get("risk", {})

        if prediction.get("status") == "insufficient_data" or rag.get("status") != "ok":
            return self._result(
                ctx.scenario,
                confidence=0.0,
                reasoning_summary="Explainability requires valid predictions and retrieved disasters.",
                evidence_items=[],
                recommendations=[],
                next_actions=[],
                status="failed",
                output={"status": "insufficient_data"},
                execution_time_ms=0,
            )

        importance_path = MODELS_DIR / "feature_importance.json"
        feature_importance = {}
        if importance_path.exists():
            feature_importance = json.loads(importance_path.read_text(encoding="utf-8"))

        prompt = (
            f"Scenario: {ctx.scenario.disaster_type} in {ctx.scenario.region}.\n"
            f"Prediction Output: {json.dumps(prediction)}\n"
            f"Feature Importance (ML model): {json.dumps(feature_importance)}\n"
            f"Risk: {json.dumps(risk)}\n\n"
            f"RAG Context:\n{rag.get('context', '')}\n\n"
            "Explain the predictions using the provided feature importance and RAG context. "
            "Output valid JSON exactly matching this structure:\n"
            "{\n"
            '  "explanations": {\n'
            '    "deaths": {"prediction": <int>, "because": ["<string>"]},\n'
            '    "affected": {"prediction": <int>, "because": ["<string>"]},\n'
            '    "damage": {"prediction": <int>, "because": ["<string>"]}\n'
            '  }\n'
            "}"
        )

        try:
            if ctx.generation_client is None:
                raise RuntimeError("NVIDIA generation client is not configured.")
            generated = await ctx.generation_client.generate(
                messages=[
                    GenerationMessage(role="system", content=f"{STRICT_REALTIME_PROMPT}\nYou are a strict JSON-only AI explainability analyst."),
                    GenerationMessage(role="user", content=prompt),
                ],
                max_tokens=800,
                temperature=0.1,
            )
            data = parse_json_object(generated.content)
            explanations = data.get("explanations", {})
        except Exception as exc:
            data = build_explanations(prediction, feature_importance, rag, risk)
            data["fallback_reason"] = str(exc)
            explanations = data.get("explanations", {})

        retrieved = rag.get("retrieved_disasters", [])
        top = retrieved[0] if retrieved else {}
        top_sim = float(top.get("similarity", 0)) if top else 0.0

        for key in ["deaths", "affected", "damage"]:
            if key in explanations:
                explanations[key]["source_disasters"] = [
                    {"id": r.get("id"), "event_name": r.get("event_name"), "similarity": r.get("similarity")}
                    for r in retrieved[:3]
                ]

        return self._result(
            ctx.scenario,
            confidence=compute_confidence(True, len(retrieved), top_sim, []),
            reasoning_summary="Dynamic explanations generated by LLM interpreting model feature importance and RAG context.",
            evidence_items=[
                evidence("explainability", "Death prediction chain", str(explanations.get("deaths", {}).get("because", []))),
            ],
            recommendations=["Present explanation chains in the executive report."],
            next_actions=["Continue to logistics and planning agents."],
            status="completed",
            output={
                "explanations": explanations,
                "feature_importance": feature_importance,
                "generation_mode": data.get("generation_mode", "nvidia-build"),
                "fallback_reason": data.get("fallback_reason"),
            },
            execution_time_ms=0,
        )
