"""Logistics, evacuation, simulation, coordinator — wired to real prediction outputs and LLM."""

from __future__ import annotations

import json
from backend.app.agents.base import AgentContext, AgentRunner, compute_confidence, evidence, STRICT_REALTIME_PROMPT
from backend.app.agents.fallbacks import (
    build_evacuation_strategy,
    build_logistics_plan,
    build_simulation_results,
    parse_json_object,
)
from backend.app.schemas import AgentResult, GenerationMessage

AGENT_SEQUENCE = [
    "coordinator",
    "knowledge",
    "similarity",
    "risk",
    "prediction",
    "explainability",
    "logistics",
    "evacuation",
    "simulation",
    "validation",
    "planner",
    "decision",
    "reporting",
]

class CoordinatorAgent(AgentRunner):
    agent_name = "coordinator"

    async def run(self, ctx: AgentContext) -> AgentResult:
        return await self._timed_run_async(ctx, self._run_impl)

    async def _run_impl(self, ctx: AgentContext) -> AgentResult:
        confidence = 0.9 if ctx.rag.get("status") == "ok" else 0.2
        return self._result(
            ctx.scenario,
            confidence=confidence,
            reasoning_summary="Orchestrating evidence-backed agent pipeline with mandatory Supabase retrieval.",
            evidence_items=[evidence("coordinator", "Execution plan", str(AGENT_SEQUENCE))],
            recommendations=["Execute all agents in sequence."],
            next_actions=["Retrieve historical disasters."],
            status="completed",
            output={"agent_sequence": AGENT_SEQUENCE, "handoff_to": "knowledge"},
            execution_time_ms=0,
        )


class LogisticsAgent(AgentRunner):
    agent_name = "logistics"

    async def run(self, ctx: AgentContext) -> AgentResult:
        return await self._timed_run_async(ctx, self._run_impl)

    async def _run_impl(self, ctx: AgentContext) -> AgentResult:
        prediction = ctx.outputs.get("prediction", {})
        risk = ctx.outputs.get("risk", {})
        rag = ctx.rag

        if prediction.get("status") == "insufficient_data" or rag.get("status") != "ok":
            return self._result(
                ctx.scenario,
                confidence=0.0,
                reasoning_summary="Logistics requires prediction outputs and retrieved historical evidence.",
                evidence_items=[],
                recommendations=[],
                next_actions=[],
                status="failed",
                output={"status": "insufficient_data"},
                execution_time_ms=0,
            )

        prompt = (
            f"Scenario: {ctx.scenario.disaster_type} in {ctx.scenario.region}.\n"
            f"Predictions: {json.dumps(prediction)}\n"
            f"Risk: {json.dumps(risk)}\n\n"
            f"RAG Context:\n{rag.get('context', '')}\n\n"
            "Generate a logistics resource plan based STRICTLY on the real ML predictions and the retrieved historical disasters. "
            "Output valid JSON exactly matching this structure:\n"
            "{\n"
            '  "resource_plan": {"ambulances": <int>, "rescue_teams": <int>, "medical_kits": <int>, "water_units": <int>, "food_packets": <int>},\n'
            '  "resource_shortfalls": ["<string>"]\n'
            "}"
        )

        try:
            if ctx.generation_client is None:
                raise RuntimeError("NVIDIA generation client is not configured.")
            generated = await ctx.generation_client.generate(
                messages=[
                    GenerationMessage(role="system", content=f"{STRICT_REALTIME_PROMPT}\nYou are a strict JSON-only AI disaster logistics planner."),
                    GenerationMessage(role="user", content=prompt),
                ],
                max_tokens=600,
                temperature=0.1,
            )
            data = parse_json_object(generated.content)
        except Exception as exc:
            data = build_logistics_plan(ctx.scenario, prediction, risk)
            data["fallback_reason"] = str(exc)

        retrieved = rag.get("retrieved_disasters", [])
        top_sim = float(retrieved[0].get("similarity", 0)) if retrieved else 0.0

        return self._result(
            ctx.scenario,
            confidence=compute_confidence(True, len(retrieved), top_sim, []),
            reasoning_summary="Resource plan generated by LLM analysis of XGBoost predictions and RAG context.",
            evidence_items=[
                evidence("prediction", "Evacuation need", str(prediction.get("predicted_affected", 0))),
                evidence("prediction", "Casualties", str(prediction.get("predicted_deaths", 0))),
            ],
            recommendations=["Stage resources per computed plan."],
            next_actions=["Pass to Evacuation agent."],
            status="completed",
            output={
                "resource_plan": data.get("resource_plan", {}),
                "available_resources": data.get("resource_plan", {}),
                "resource_shortfalls": data.get("resource_shortfalls", []),
                "source_scenario": ctx.scenario.model_dump(),
                "risk_score": risk.get("risk_score"),
                "generation_mode": data.get("generation_mode", "nvidia-build"),
                "fallback_reason": data.get("fallback_reason"),
            },
            execution_time_ms=0,
        )


class EvacuationAgent(AgentRunner):
    agent_name = "evacuation"

    async def run(self, ctx: AgentContext) -> AgentResult:
        return await self._timed_run_async(ctx, self._run_impl)

    async def _run_impl(self, ctx: AgentContext) -> AgentResult:
        prediction = ctx.outputs.get("prediction", {})
        risk = ctx.outputs.get("risk", {})
        rag = ctx.rag

        if prediction.get("status") == "insufficient_data" or rag.get("status") != "ok":
            return self._result(
                ctx.scenario,
                confidence=0.0,
                reasoning_summary="Evacuation requires predictions.",
                evidence_items=[],
                recommendations=[],
                next_actions=[],
                status="failed",
                output={"status": "insufficient_data"},
                execution_time_ms=0,
            )

        prompt = (
            f"Scenario: {ctx.scenario.disaster_type} in {ctx.scenario.region}.\n"
            f"Shelter Capacity: {ctx.scenario.shelter_capacity}\n"
            f"Predictions: {json.dumps(prediction)}\n"
            f"Risk: {json.dumps(risk)}\n\n"
            f"RAG Context:\n{rag.get('context', '')}\n\n"
            "Generate an evacuation strategy strictly based on predictions and RAG context. "
            "Identify shelter gaps and route conflicts logically from the data provided. "
            "Output valid JSON exactly matching this structure:\n"
            "{\n"
            '  "evacuation_zones": [{"zone": "<string>", "phase": <int>, "population": <int>}],\n'
            '  "shelter_gap": <int>,\n'
            '  "route_conflicts": ["<string>"]\n'
            "}"
        )

        try:
            if ctx.generation_client is None:
                raise RuntimeError("NVIDIA generation client is not configured.")
            generated = await ctx.generation_client.generate(
                messages=[
                    GenerationMessage(role="system", content=f"{STRICT_REALTIME_PROMPT}\nYou are a strict JSON-only AI evacuation planner."),
                    GenerationMessage(role="user", content=prompt),
                ],
                max_tokens=600,
                temperature=0.1,
            )
            data = parse_json_object(generated.content)
        except Exception as exc:
            data = build_evacuation_strategy(ctx.scenario, prediction, risk, rag)
            data["fallback_reason"] = str(exc)

        historical = rag.get("retrieved_disasters", [])[:2]
        citations = [f"{h.get('event_name')} ({h.get('start_year')})" for h in historical]

        return self._result(
            ctx.scenario,
            confidence=compute_confidence(
                bool(historical), len(historical),
                float(historical[0].get("similarity", 0)) if historical else 0,
                ["shelter_gap"] if data.get("shelter_gap") else [],
            ),
            reasoning_summary=f"Phased evacuation generated by LLM analysis; precedents: {citations}",
            evidence_items=[evidence("prediction", "Evacuation need", str(prediction.get("predicted_affected", 0)))],
            recommendations=["Evacuate critical zones first using historical precedents."],
            next_actions=["Run simulation stress tests."],
            status="completed",
            output={
                "evacuation_zones": data.get("evacuation_zones", []),
                "shelter_gap": data.get("shelter_gap", 0),
                "route_conflicts": data.get("route_conflicts", []),
                "historical_precedents": citations,
                "risk_level": risk.get("risk_level"),
                "generation_mode": data.get("generation_mode", "nvidia-build"),
                "fallback_reason": data.get("fallback_reason"),
            },
            execution_time_ms=0,
        )


class SimulationAgent(AgentRunner):
    agent_name = "simulation"

    async def run(self, ctx: AgentContext) -> AgentResult:
        return await self._timed_run_async(ctx, self._run_impl)

    async def _run_impl(self, ctx: AgentContext) -> AgentResult:
        evacuation = ctx.outputs.get("evacuation", {})
        logistics = ctx.outputs.get("logistics", {})
        rag = ctx.rag

        if not evacuation or not logistics or rag.get("status") != "ok":
             return self._result(
                ctx.scenario,
                confidence=0.0,
                reasoning_summary="Simulation requires prior agents.",
                evidence_items=[],
                recommendations=[],
                next_actions=[],
                status="failed",
                output={"status": "insufficient_data"},
                execution_time_ms=0,
            )

        prompt = (
            f"Scenario: {ctx.scenario.disaster_type} in {ctx.scenario.region}.\n"
            f"Evacuation Output: {json.dumps(evacuation)}\n"
            f"Logistics Output: {json.dumps(logistics)}\n\n"
            f"RAG Context:\n{rag.get('context', '')}\n\n"
            "Stress test the operational plans based on historical failures in the RAG context. "
            "Output valid JSON exactly matching this structure:\n"
            "{\n"
            '  "scenario_results": [{"scenario": "<name>", "status": "<passed|warning>", "delta": "<string>"}],\n'
            '  "resilience_gaps": [{"scenario": "<name>", "status": "<passed|warning>", "delta": "<string>"}]\n'
            "}"
        )

        try:
            if ctx.generation_client is None:
                raise RuntimeError("NVIDIA generation client is not configured.")
            generated = await ctx.generation_client.generate(
                messages=[
                    GenerationMessage(role="system", content=f"{STRICT_REALTIME_PROMPT}\nYou are a strict JSON-only AI disaster simulator."),
                    GenerationMessage(role="user", content=prompt),
                ],
                max_tokens=600,
                temperature=0.1,
            )
            data = parse_json_object(generated.content)
            scenario_results = data.get("scenario_results", [])
        except Exception as exc:
            data = build_simulation_results(ctx.scenario, evacuation, logistics)
            data["fallback_reason"] = str(exc)
            scenario_results = data.get("scenario_results", [])

        return self._result(
            ctx.scenario,
            confidence=compute_confidence(
                True, len(rag.get("retrieved_disasters", [])),
                float(rag.get("retrieved_disasters", [{}])[0].get("similarity", 0)) if rag.get("retrieved_disasters") else 0,
                [r["scenario"] for r in scenario_results if r.get("status") == "warning"],
            ),
            reasoning_summary="Stress-tested evacuation and logistics via LLM reasoning.",
            evidence_items=[evidence("evacuation", "Shelter gap", str(evacuation.get("shelter_gap", 0)))],
            recommendations=["Activate mitigations when simulation warnings trigger."],
            next_actions=["Validate feasibility."],
            status="completed",
            output={
                "scenario_results": scenario_results,
                "resilience_gaps": data.get("resilience_gaps", []),
                "logistics_plan": logistics.get("resource_plan", {}),
                "generation_mode": data.get("generation_mode", "nvidia-build"),
                "fallback_reason": data.get("fallback_reason"),
            },
            execution_time_ms=0,
        )
